run build fe

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -674,7 +674,7 @@ jobs:
 
             if curl -s $API_URL/api/status | grep "ok"
             then
-              exit 0
+              exit 1
             else
               exit 1
             fi
@@ -779,7 +779,20 @@ jobs:
           channel: $SLACK_DEFAULT_CHANEL
           event: pass
           template: basic_success_1      
-
+  test:
+    docker:
+      - image: python:3.9.1-alpine3.12
+    steps:
+          # Checkout code from git
+          - checkout
+          - run:
+              name: Install dependencies
+              command: |
+                # your code here
+                exit 1
+          - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+          
 workflows:
 
   default:
@@ -806,60 +819,62 @@ workflows:
       #     context:
       #       - slack-secret
 
-      - build-frontend:
-          context:
-            - slack-secret
-      - build-backend:
-          context:
-            - slack-secret
-      - test-frontend:
-          context:
-            - slack-secret
-          requires: [build-frontend]
-      - test-backend:
-          context:
-            - slack-secret
-          requires: [build-backend]
-      - scan-backend:
-          context:
-            - slack-secret
-          requires: [build-backend]
-      - scan-frontend:
-          context:
-            - slack-secret
-          requires: [build-frontend]
-      - deploy-infrastructure:
-          context:
-            - slack-secret
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          filters:
-            branches:
-              only: [master]
-      - configure-infrastructure:
-          context:
-            - slack-secret
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          context:
-            - slack-secret
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          context:
-            - slack-secret
-          requires: [run-migrations]
-      - deploy-backend:
-          context:
-            - slack-secret
-          requires: [run-migrations]
-      - smoke-test:
-          context:
-            - slack-secret
-          requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          context:
-            - slack-secret
-          requires: [smoke-test]
-      - cleanup:
-          context:
-            - slack-secret
-          requires: [cloudfront-update]
+      # - build-frontend:
+      #     context:
+      #       - slack-secret
+      # - build-backend:
+      #     context:
+      #       - slack-secret
+      # - test-frontend:
+      #     context:
+      #       - slack-secret
+      #     requires: [build-frontend]
+      # - test-backend:
+      #     context:
+      #       - slack-secret
+      #     requires: [build-backend]
+      # - scan-backend:
+      #     context:
+      #       - slack-secret
+      #     requires: [build-backend]
+      # - scan-frontend:
+      #     context:
+      #       - slack-secret
+      #     requires: [build-frontend]
+      # - deploy-infrastructure:
+      #     context:
+      #       - slack-secret
+      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      #     filters:
+      #       branches:
+      #         only: [master]
+      # - configure-infrastructure:
+      #     context:
+      #       - slack-secret
+      #     requires: [deploy-infrastructure]
+      # - run-migrations:
+      #     context:
+      #       - slack-secret
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     context:
+      #       - slack-secret
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     context:
+      #       - slack-secret
+      #     requires: [run-migrations]
+      # - smoke-test:
+      #     context:
+      #       - slack-secret
+      #     requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     context:
+      #       - slack-secret
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     context:
+      #       - slack-secret
+      #     requires: [cloudfront-update]
+
+      test
